# LOGGING
logging:
  level:
   org.springframework.web: DEBUG


  # APPLICATION
spring:
  application:
   name: turkcell-crm-order-management


kafka-client-id: crmorderclient
kafka-bootstrap-servers: localhost:9092
kafka-producer-key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
kafka-producer-value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka-order-topic: crmorder

server:
  port: 8084
